all: SumOfDigits PrimeNumber

SumOfDigits:
	javac SumOfDigits.java
	java SumOfDigits

PrimeNumber:
	javac PrimeNumber.java
	java PrimeNumber 

LinePermutation:
	javac LinePermutation.java
	java LinePermutation

clean:
	rm -rf *.class